name: Docker build pulsejet go-vod image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    paths:
      - '.github/workflows/docker-build-pulsejet-go-vod.yml'
      - 'go-vod/**'

jobs:

  build:

    runs-on: ${{ (github.event_name == 'push') && fromJSON('[ "buildjet-16vcpu-ubuntu-2204" ]') || 'ubuntu-latest' }}

    steps:
      - name: Get latest tag
        id: get-latest-tag
        run: |
          echo "tag=$(git ls-remote --refs --tags https://github.com/pulsejet/go-vod.git|cut --delimiter='/' --fields=3|sort --version-sort|tail --lines=1)" >> $GITHUB_ENV
        shell: bash

      - uses: actions/cache@v2
        id: cache
        with:
          path: pulsejet-go-vod
          key: ${{ runner.os }}-v1-${{ env.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          platforms: all

      - name: Check Out Repo
        uses: actions/checkout@v3
          
      - name: Check Out Repo pulsejet/go-vod
        uses: actions/checkout@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          repository: "pulsejet/go-vod"
          ref: '${{ env.tag }}'
          path: 'pulsejet-go-vod-git'

      - name: Login to Quay.io
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up Docker Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Build and push docker image go-vod
        if: steps.cache.outputs.cache-hit != 'true'
        id: docker_build_new_single_process
        uses: docker/build-push-action@v3
        with:
          context: ./pulsejet-go-vod-git
          file: ./pulsejet-go-vod-git/Dockerfile
          platforms: linux/amd64
          push: true
          tags: quay.io/unixfox/pulsejet-go-vod:latest, quay.io/unixfox/pulsejet-go-vod:${{ env.tag }}-${{ env.timestamp }}