name: Docker build openresty-ssl-ja3 image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    paths:
      - '.github/workflows/docker-build-openresty-ssl-ja3.yml'
      - 'openresty-ssl-ja3/**'

jobs:

  build:

    runs-on: ubuntu-24.04-arm

    steps:
      - name: Get latest commit hash
        id: get-latest-commit
        run: |
          echo "commit=$(git ls-remote https://github.com/fooinha/nginx-ssl-ja3.git | head -n1 | awk '{print $1;}')" >> $GITHUB_ENV
        shell: bash

      - uses: actions/cache@v4
        id: cache
        with:
          path: openresty-ssl-ja3
          key: ${{ runner.os }}-v7-${{ env.commit }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   with:
      #     platforms: all

      - name: Set number of cores
        run: |
          echo "NUMBER_OF_CORES=$(nproc)" >> $GITHUB_ENV

      - name: Check Out Repo openresty/docker-openresty
        uses: actions/checkout@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          repository: "openresty/docker-openresty"
          ref: 'master'

      - name: Check Out Repo
        uses: actions/checkout@v3
        with:
          path: 'periodic-build'
          
      - name: Login to Quay.io
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up Docker Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Set up build timestamp
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "timestamp=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Build and push docker image
        if: steps.cache.outputs.cache-hit != 'true'
        id: docker_build_new
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./periodic-build/openresty-ssl-ja3/Dockerfile
          platforms: linux/arm64
          push: true
          build-args: |
            RESTY_J=${{ env.NUMBER_OF_CORES }}
          tags: quay.io/unixfox/openresty-ssl-ja3:openssl3w-nginx1271-latest, quay.io/unixfox/openresty-ssl-ja3:openssl3w-nginx1271-${{ env.timestamp }}