name: Docker build stash image

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/docker-build-stash.yml'
      - 'stash/**'

jobs:

  build:

    runs-on: 'ubuntu-latest'

    steps:
      - name: Get latest tag
        id: get-latest-tag
        run: |
          echo "tag=$(git ls-remote --refs --tags https://github.com/stashed/stash.git|cut --delimiter='/' --fields=3|sort --version-sort|tail --lines=1)" >> $GITHUB_ENV
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Check Out Repo
        uses: actions/checkout@v5
          
      - name: Check Out Repo stashed/stash
        uses: actions/checkout@v5
        with:
          repository: "stashed/stash"
          ref: '${{ env.tag }}'
          path: 'stash-git'

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Replace rest by rclone and copy modified Dockerfile
        id: replace-copy
        run: |
          sed -i 's/rest:/rclone:/' stash-git/vendor/stash.appscode.dev/apimachinery/pkg/restic/setup.go
          cp stash/Dockerfile.in stash-git/Dockerfile.in
        shell: bash

      - name: Publish docker image
        env:
          REGISTRY: quay.io/unixfox
          DOCKER_TOKEN: ${{ secrets.QUAY_PASSWORD }}
          USERNAME: ${{ secrets.QUAY_USERNAME }}
          APPSCODE_ENV: prod
        run: |
          docker login quay.io --username ${USERNAME} --password ${DOCKER_TOKEN}
          cd stash-git && make release