name: Docker build nitter patched docker image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    paths:
      - '.github/workflows/docker-build-nitter-patched.yml'
      - 'nitter/**'

jobs:

  build:

    runs-on: ubuntu-24.04-arm

    steps:      
      - name: Get latest commit
        id: get-latest-commit
        run: |
          echo "commit=$(git ls-remote https://github.com/zedeus/nitter.git | head -n1 | awk '{print $1;}')" >> $GITHUB_ENV
        shell: bash

      - uses: actions/cache@v4
        id: cache
        with:
          path: nitter
          key: ${{ runner.os }}-v3-${{ env.commit }}

      - name: Check Out Repo
        uses: actions/checkout@v3
          
      - name: Check Out Repo zedeus/nitter
        uses: actions/checkout@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          repository: "zedeus/nitter"
          ref: 'master'
          path: 'nitter-git'

      - name: patch nitter master repo
        if: steps.cache.outputs.cache-hit != 'true' 
        run: |
          cd nitter-git
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git am ../nitter/patches/*.patch
      
      - name: Login to Quay.io
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up Docker Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Set up build timestamp
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "timestamp=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Build and push patched nitter
        if: steps.cache.outputs.cache-hit != 'true'
        id: docker_build_new_custom
        uses: docker/build-push-action@v3
        with:
          context: ./nitter-git
          file: ./nitter-git/Dockerfile
          platforms: linux/arm64/v8
          push: true
          tags: quay.io/unixfox/nitter-patched:latest, quay.io/unixfox/nitter-patched:${{ env.commit }}-${{ env.timestamp }}
