name: Docker build gpt4free image

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/docker-build-gpt4free.yml'

jobs:
  build:
    runs-on: 'ubuntu-24.04-arm'

    steps:      
      - name: Get latest commit hash
        id: get-latest-commit
        run: |
          echo "commit=$(git ls-remote https://github.com/xtekky/gpt4free.git | head -n1 | awk '{print $1;}')" >> $GITHUB_ENV
        shell: bash

      - name: Check Out Repo
        uses: actions/checkout@v3
          
      - name: Check Out Repo gpt4free
        uses: actions/checkout@v3
        with:
          repository: "xtekky/gpt4free"
          ref: 'main'
          path: 'gpt4free-git'

      - name: Use docker base image that supports arm64
        run: |
          sed -i 's|selenium/node-chrome|selenium/node-chromium|' gpt4free-git/docker/Dockerfile
          
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Set up build timestamp
        run: echo "timestamp=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Build and push docker image
        id: docker_build_new
        uses: docker/build-push-action@v3
        with:
          context: ./gpt4free-git
          file: ./gpt4free-git/docker/Dockerfile
          platforms: linux/arm64
          push: true
          tags: quay.io/unixfox/gpt4free:latest, quay.io/unixfox/gpt4free:build-${{ env.timestamp }} 
