name: Docker build cert-manager-webhook-powerdns image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    paths:
      - '.github/workflows/docker-build-cert-manager-webhook-powerdns.yml'
      - 'cert-manager-webhook-powerdns/**'

jobs:

  build:

    runs-on: 'ubuntu-latest'

    steps:
      - name: Get latest commit hash
        id: get-latest-commit
        run: |
          echo "commit=$(git ls-remote https://github.com/lordofsystem/cert-manager-webhook-powerdns.git | head -n1 | awk '{print $1;}')" >> $GITHUB_ENV
        shell: bash

      - uses: actions/cache@v4
        id: cache
        with:
          path: cert-manager-webhook-powerdns
          key: ${{ runner.os }}-v1-${{ env.commit }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          platforms: all

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Check Out Repo lordofsystem/cert-manager-webhook-powerdns
        uses: actions/checkout@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          repository: "lordofsystem/cert-manager-webhook-powerdns"
          ref: 'main'
          path: 'cert-manager-webhook-powerdns-git'
          
      - name: Login to Quay.io
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up Docker Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Set up build timestamp
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "timestamp=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Build and push docker image
        if: steps.cache.outputs.cache-hit != 'true'
        id: docker_build_new
        uses: docker/build-push-action@v3
        with:
          context: ./cert-manager-webhook-powerdns-git
          file: ./cert-manager-webhook-powerdns-git/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/unixfox/cert-manager-webhook-powerdns:latest, quay.io/unixfox/cert-manager-webhook-powerdns:build-${{ env.timestamp }}